const FIRST_VALUE = prompt('Введите значение');
const SECOND_VALUE = prompt('Введите значение');
const VALUE_TO_CONVERT = parseInt(FIRST_VALUE);
const SYSTEM_TO_CONVERT_VALUE_IN = parseInt(SECOND_VALUE);
const IS_VALUE_INVALID = !VALUE_TO_CONVERT || !SYSTEM_TO_CONVERT_VALUE_IN || SYSTEM_TO_CONVERT_VALUE_IN < 2 || SYSTEM_TO_CONVERT_VALUE_IN > 36;
const CONVERTED_VALUE = (!!IS_VALUE_INVALID) ? 'Некорректный ввод!' : VALUE_TO_CONVERT.toString(SYSTEM_TO_CONVERT_VALUE_IN);
console.log(CONVERTED_VALUE);